### ISSUE TITLE
Not working in .NET Core 2.1

### ISSUE THREAD

**Issue by radenkozec** [MihaiBogdanEugen/StackExchange.Exceptional.PostgreSql#1]
I am trying this to make work in .NET Core 2.1 project without success.
My appsettings.json looks like this:
` "Exceptional": {
    "ApplicationName": "LanacoIntSrv",
    "ErrorStore": {
      "Type": "PostgreSql",
      "ConnectionString": "Server=localhost;Port=5432;Database=lanacointsrv;User Id=admin;Password=admin;"
    }`
I added exceptional like this
```
  services.AddExceptional(Configuration.GetSection("Exceptional"),
            settings =>
            {
               settings.UseExceptionalPageOnThrow = HostingEnvironment.IsDevelopment();

            });
```
When I throw the error it is stated that memory store is used.
Any tips?

**Comment by MihaiBogdanEugen** [comment]
Hey there,

When I've started this project a while ago, I had no goal in mind to offer support for .NET Core, simply because I wasn't using it.

About 6 months ago, the original author of the StackExchange.Exceptional package (Nick Craver) decided to do a similar one, so gave him the "naming rights". Nuget does a poor job in highlighting this, so my package can be found [here](https://github.com/MihaiBogdanEugen/StackExchange.Exceptional.PostgreSql), his official package (that has .NET Core support as far as I know), can be found [here](https://github.com/NickCraver/StackExchange.Exceptional). Please address your support questions [there](https://github.com/NickCraver/StackExchange.Exceptional/issues), and make sure you're using the correct [Nuget package](https://www.nuget.org/packages/StackExchange.Exceptional.PostgreSql/2.0.0-rc2.28).

As of this repo, it is unofficially abandoned, I'll update the README asap.

Best regards,
B.

**Comment by radenkozec** [comment]
Thanks
